[package]
name = "backset"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3"
actix-cors = "0.6"
dotenv = "0.15"
env_logger = "0.10.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.6", features = ["runtime-async-std-native-tls", "postgres", "offline", "macros"] }
