[package]
name = "backset"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "backset"

[dependencies]
actix-web = "4.3"
actix-web-validator = "5.0"
actix-http = "3.3"
anyhow = "1.0"
dotenv = "0.15"
env_logger = "0.10.0"
lazy_static = "1.4"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.6", features = ["runtime-async-std-native-tls", "postgres", "offline", "macros", "chrono"] }
thiserror = "1.0"
validator = { version = "0.16", features = ["derive"] }
strum = "0.24"
strum_macros = "0.24"
rand = "0.8"
chrono = { version = "0.4", features = ["serde"] }
