services:
  pg-bss:
    image: postgres
    container_name: pg-bss
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    #command: ["postgres", "-c", "log_statement=all"]  # Comment to disable SQL logs. all: all queries, ddl: DDL only, mod: DDL and modifying statements

  psql:
    image: postgres
    command: psql postgres -h pg-bss -U postgres -W
    depends_on:
      - pg-bss
    profiles:       # To avoid the container start with `docker compose up'
      - tools

volumes:
  data:             # Volume name listed: backset_data
    driver: local

# - `docker compose up' to start postgres attached to the console. Add `-d' option
#   to start the container detached
# - Connect with `docker compose run psql`. To pass more options to `psql' use:
#   `docker compose run pg-bss psql postgres -h HOSTIP -U postgres -W [OPTIONS...]'
# - Run any pg_* command available in the container, e.g.
#   `docker compose run pg-bss pg_dump [OPTIONS]`
# - `docker compose stop' to stop the service if it was detached,
#    otherwise just press Ctrl+C to stop
# - `docker compose down' to shutdown and drop the container (the data will continue
#   stored in the 'backset_data' volume)
# - `docker volume rm backset_data' to drop the data from the volume (first
#   execute `docker compose down')
# - `~/bin/docker-volume-cp backset_data backset_data-backup-$(date --iso-8601)'
#   to backup the DB to a new volume
