name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: SQLX_OFFLINE=true cargo build --verbose
#    - name: Lint
#      run: SQLX_OFFLINE=true cargo clippy -- -D warnings
#    - name: Format Check
#      run: SQLX_OFFLINE=true cargo fmt -- --check
#    - name: Run tests
#      run: SQLX_OFFLINE=true cargo test --verbose
