name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create .env file
      run: cp .env.example .env
    - name: Install SQLx
      run: cargo install sqlx-cli --no-default-features --features native-tls,postgres
    - name: Run PostgreSQL
      run: docker compose up -d
    - name: Wait DB
      run: sleep 5
    - name: Migrations
      run: make recreate-db
    - name: Build
      run: make build
    - name: Lint
      run: make lint
#    - name: Format Check
#      run: make fmt-check
    - name: Tests
      run: make test
