name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Create .env file
      run: cp .env.example .env
    - name: Install SQLx
      run: RUSTFLAGS='-C strip=symbols' cargo install sqlx-cli --no-default-features --features native-tls,postgres
    - name: Run PostgreSQL
      run: docker compose up postgres -d
    - name: Wait DB
      run: make wait-pg
    - name: Migrations
      run: make recreate-db
    - name: Build
      run: make build
    - name: Lint
      run: make lint
#    - name: Format Check
#      run: make fmt-check
    - name: Tests
      run: make test
    - name: Run server
      run: make run &
    - name: Wait Server
      run: make wait-server
    - name: Check server
      run: make health
