name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run DB
      run: docker compose up -d
    - name: Migrations
      run: make recreate-db
    - name: Build
      run: make build
    - name: Lint
      run: make lint
#    - name: Format Check
#      run: make fmt-check
    - name: Tests
      run: make test
